language: cpp
sudo: required
dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  
      # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'g++-7']
      env:
        - CXX=clang++-6.0

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-7']
      env:
        - CXX=clang++-7

before_install:
    - sudo apt-get update
    - sudo apt-get install libhiredis-dev
    - sudo apt-get install libmysqlcppconn-dev
    - cd ~
    - git clone git@github.com:ZingLix/psyche.git
    - cd psyche
    - cmake .
    - make && sudo make install
    - cd ~
    - git clone https://github.com/Tencent/rapidjson.git
    - sudo cp -r include /usr/include
    - eval "${MATRIX_EVAL}"
script: cmake . && make

notifications:
  email: false